# Server configured to port 5200
server:
  port: 5200


# Spring configurations to include secret YAML file
spring:
  config:
    import:
      - "application-secret.yaml"
      - "application-tool.yaml"
      - "application-llm.yaml"