#######################################################################################
# This is a file that contains all the configuration details related to LLMs          #
# for the agent. Use this file to store all relevant (public) information             #
# regarding the LLMs so that it is always easier to modify details as per the         #
# needs of the agent, as well as the APIs                                             #
#                                                                                     #
# Author : amanfoundongithub                                                          #
#######################################################################################


# Ollama Service Configurations
ollama_service:
  model: llama3.2
  description: Ollama service for LLM
  url: http://127.0.0.1:8000/api/llm/generate

