


# Spring configuration
spring:
  application:
    name: agent

  redis:
    host: localhost
    port: 6379
    timeout: 2000

  data:
    mongodb:
      host: localhost
      port: 27017
      database: agentic_ai

  config:
    import:
      - "application-secret.yaml"
      - "application-tool.yaml"
      - "application-llm.yaml"


# Server configured to port 6900
server:
  port: 6900

# WebClient configurations
web_client:
  timeoutInSeconds: 180


# Configuration for JOB
job:
  pool_size: 4
  max_pool_size: 6
  max_queue_size: 1000
  thread_workers_prefix: Agent_Worker